
server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

#spring:
#  datasource:
#    url: 'jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE'
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true